### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by sexta13**
The main goal of this PR is to improve some code aspects:
1 - Separate all the HTML logic from the challengeService. ChallengeService should be to be used to obtain challenge information, not to generate html to show in the views.
2 - Notifications - created an helper to show notifications. If by some reason it is necessary to change the way notifications are shown, this is the only file necessary to adapt. 
3 - Fixed error when no reviews - show a message: "No reviews to show". The same for artifacts.
4 - Created a new unit test file to test html helper. Moved tests from challenge test unit file to this one.

### CODE REVIEW

**Comment by callmekatootie** [comment]
@sexta13  4 tests fail

The first 2 seem to fail in `develop` branch as well but the next two are the ones from this PR:

image

**Comment by sexta13** [comment]
MBP-de-Sergio:ide-ext-vscode sexta13$ sudo npm run test
Password:

> tcvscodeide@0.0.1 test /Users/sexta13/projects/topcoder/ide-ext-vscode
> npm run compile && node ./out/test/runTest.js


> tcvscodeide@0.0.1 compile /Users/sexta13/projects/topcoder/ide-ext-vscode
> tsc -p ./ && npm run copy:resources


> tcvscodeide@0.0.1 copy:resources /Users/sexta13/projects/topcoder/ide-ext-vscode
> copyfiles resources/**/* out

Downloading VS Code 1.38.1 from https://update.code.visualstudio.com/1.38.1/darwin/stable
Downloaded VS Code 1.38.1 into .vscode-test/vscode-1.38.1
[main 2019-09-14T17:45:38.691Z] update#setState idle

[tcvscodeide] The extension is active.





  AuthService Unit tests

logging in user: callmekatootie

{ AUTHN_URL: 'https://topcoder-dev.auth0.com/oauth/ro',
  AUTHZ_URL: 'https://api.topcoder-dev.com/v3/authorizations',
  CLIENT_ID: 'JFDo7HMkf0q2CkVFHojy3zHWafziprhT',
  CLIENT_V2CONNECTION: 'TC-User-Database' }

exchanging v2Token for v3Token

received v3 token

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6Im1lc3MiLCJleHAiOjE1NTkzMzU4NjUsInVzZXJJZCI6Ijk5OTk4ODg4IiwiaWF0IjoxNTU5MzM1MjY1LCJlbWFpbCI6Im1lc3NAZXhhbXBsZS5jb20iLCJqdGkiOiIxYmZiNzExNi0xNjBmLTQxMGQtYjM2MC1hYzM3NDFkZDM3NWQifQ.6Kmb_VmH3LFPJGXYk6hOQ9NN1QI9IvXb33kMpb_QBkQ

    ✓ fetchToken() should fetch a new token (78ms)

    ✓ refreshToken() should refresh the token

Fetching new token.

logging in user: callmekatootie

{ AUTHN_URL: 'https://topcoder-dev.auth0.com/oauth/ro',
  AUTHZ_URL: 'https://api.topcoder-dev.com/v3/authorizations',
  CLIENT_ID: 'JFDo7HMkf0q2CkVFHojy3zHWafziprhT',
  CLIENT_V2CONNECTION: 'TC-User-Database' }
exchanging v2Token for v3Token

received v3 token

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6Im1lc3MiLCJleHAiOjE1NTkzMzU4NjUsInVzZXJJZCI6Ijk5OTk4ODg4IiwiaWF0IjoxNTU5MzM1MjY1LCJlbWFpbCI6Im1lc3NAZXhhbXBsZS5jb20iLCJqdGkiOiIxYmZiNzExNi0xNjBmLTQxMGQtYjM2MC1hYzM3NDFkZDM3NWQifQ.6Kmb_VmH3LFPJGXYk6hOQ9NN1QI9IvXb33kMpb_QBkQ

    ✓ getToken() without previous saved token should fetch a new token

Fetching new token.

logging in user: callmekatootie

{ AUTHN_URL: 'https://topcoder-dev.auth0.com/oauth/ro',
  AUTHZ_URL: 'https://api.topcoder-dev.com/v3/authorizations',
  CLIENT_ID: 'JFDo7HMkf0q2CkVFHojy3zHWafziprhT',
  CLIENT_V2CONNECTION: 'TC-User-Database' }

exchanging v2Token for v3Token

received v3 token

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLmNvbSIsImhhbmRsZSI6Im1lc3MiLCJleHAiOjE1NTkzMzU4NjUsInVzZXJJZCI6Ijk5OTk4ODg4IiwiaWF0IjoxNTU5MzM1MjY1LCJlbWFpbCI6Im1lc3NAZXhhbXBsZS5jb20iLCJqdGkiOiIxYmZiNzExNi0xNjBmLTQxMGQtYjM2MC1hYzM3NDFkZDM3NWQifQ.6Kmb_VmH3LFPJGXYk6hOQ9NN1QI9IvXb33kMpb_QBkQ

    ✓ getToken() with invalid token should fetch a new token (52ms)

Refreshing expired token.

    ✓ getToken() with expired token should refresh the token

    ✓ isTokenExpired() should return true when the token is expired

    ✓ isTokenExpired() should return false when the token is not expired



  ChallengeService Unit tests

    ✓ getActiveChallenges() should return the challenges list (42ms)

    ✓ uploadSubmmission() success should return success response (703ms)

    ✓ uploadSubmmission() with invalid token should throw error

    ✓ uploadSubmmission() in an nonexist workspace should throw error

    ✓ uploadSubmmission() in a workspace without .topcoderrc should throw error

    ✓ uploadSubmmission() in a workspace without .topcoderrc which does not has field challengeId should throw error

    ✓ uploadSubmmission() to an invalid challenge should throw error

    ✓ uploadSubmmission() to an unregistered challenge should throw error

    ✓ uploadSubmmission() to a challenge closed for submission should throw error

    ✓ getChallengeDetails() should return the challenge details

    ✓ getChallengeDetails() should throw exception if challenge doesnt exist

    ✓ initialize workspace action should create .topcoderrc file in root directory of workspace

    ✓ initialize workspace action should enter correct challenge id in .topcoderrc

    ✓ get active challenges of user should return the challenges with valid token

    ✓ get active challenges of user should fail with invalid token

    ✓ getSubmissionDetails() should return the submission details

    ✓ getSubmissionDetails() get submission details should fail with invalid token

    ✓ getSubmissionArtifacts() should return the submission artifacts

    ✓ getSubmissionArtifacts() get submission artifacts should fail with invalid token

    ✓ downloadArtifact() should return a file

    ✓ downloadArtifact() should fail with invalid token



  Html Unit tests

    ✓ register button should be invisible if user has registered

    ✓ register button should be visible if user can register

    ✓ initialize workspace button should be available

    ✓ artifacts should be visible in submission details html

    ✓ artifacts should not be visible in submission details html





  33 passing (1s)



Exit code:   0
Done



This is what I have when running tests. I have to run them as sudo user due to some issues with permissions, that I have not yet figure it out. But its been like that since the begining.

**Comment by sexta13** [comment]
and now that i'm seeing better, there are not 49 tests in the solution. Only 33...

**Comment by callmekatootie** [comment]
Just tried again. I updated my VSCode instance to 1.38.1 and I still see 49 passing, 4 failing for the tests. Might be something I am doing wrong. Will get a second opinion

**Comment by callmekatootie** [comment]
On closer observation, the same tests are running twice - not sure why...

**Comment by callmekatootie** [comment]
Managed to get it working
- Deleted `out` folder and `.vscode-test` folders. This resolved the duplicate tests issue. Still 1 test failed
- On debugging, found some missing packages issue - so deleted package-lock.json
- Ran tests again and this time it worked.

**Pull request merged**
